### ISSUE TITLE
Túl régi lista

### ISSUE THREAD

**Issue by t1csi** [csgerg/alternativenewsblocker#4]
Szia Gergő!

A tiltandó oldalak listája aktualizálásra szorul.
A saját forkban ezt megtettem, küldtem "pull request"-et.

Üdv:

T

**Comment by csgerg** [comment]
Köszönöm a frissítést!
Meghívhatlak collaborator-nak?

**Comment by t1csi** [comment]
Köszönöm a beolvasztást!
Igen, Megtisztelsz vele.
T
